# Generated by Django 5.2.17 on 2026-10-06 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledgerentry',
            options={'ordering': ['id'], 'verbose_name': 'Ledger entry', 'verbose_name_plural': 'Ledger entries'},
        ),
    ]
